GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "joaoppt@hotmai.com",
  "password": "password"
}

###

DELETE http://localhost:3000/users/28bb0ad8-3a6f-4a32-b479-59973e79ba4e
