POST http://localhost:3000/accounts
Content-Type: application/json
Authorization: 

{
  "balance": 0,
  "description": "Conta corrente",
  "categoryId": 1
}


####
GET http://localhost:3000/accounts
Authorization: 